// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: hoyolib_pb/hoyolib.proto

package hoyolib_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                      ErrorCode = 0
	ErrorCode_INVALID_REQUEST_PARAM   ErrorCode = 10000
	ErrorCode_ERROR_CREATE_USER       ErrorCode = 10001
	ErrorCode_ERROR_USER_NOT_REGISTER ErrorCode = 10002
	ErrorCode_ERROR_CHECK_IN          ErrorCode = 10003
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:     "OK",
		10000: "INVALID_REQUEST_PARAM",
		10001: "ERROR_CREATE_USER",
		10002: "ERROR_USER_NOT_REGISTER",
		10003: "ERROR_CHECK_IN",
	}
	ErrorCode_value = map[string]int32{
		"OK":                      0,
		"INVALID_REQUEST_PARAM":   10000,
		"ERROR_CREATE_USER":       10001,
		"ERROR_USER_NOT_REGISTER": 10002,
		"ERROR_CHECK_IN":          10003,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_hoyolib_pb_hoyolib_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_hoyolib_pb_hoyolib_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{0}
}

type GameType int32

const (
	GameType_UNKNOWN_GAME GameType = 0
	GameType_Genshin      GameType = 1000
	GameType_StarRail     GameType = 1001
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0:    "UNKNOWN_GAME",
		1000: "Genshin",
		1001: "StarRail",
	}
	GameType_value = map[string]int32{
		"UNKNOWN_GAME": 0,
		"Genshin":      1000,
		"StarRail":     1001,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_hoyolib_pb_hoyolib_proto_enumTypes[1].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_hoyolib_pb_hoyolib_proto_enumTypes[1]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{1}
}

type RegisterRequest_AccountType int32

const (
	RegisterRequest_UNKNOWN RegisterRequest_AccountType = 0
	RegisterRequest_OVERSEA RegisterRequest_AccountType = 1
	RegisterRequest_CN      RegisterRequest_AccountType = 2
)

// Enum value maps for RegisterRequest_AccountType.
var (
	RegisterRequest_AccountType_name = map[int32]string{
		0: "UNKNOWN",
		1: "OVERSEA",
		2: "CN",
	}
	RegisterRequest_AccountType_value = map[string]int32{
		"UNKNOWN": 0,
		"OVERSEA": 1,
		"CN":      2,
	}
)

func (x RegisterRequest_AccountType) Enum() *RegisterRequest_AccountType {
	p := new(RegisterRequest_AccountType)
	*p = x
	return p
}

func (x RegisterRequest_AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterRequest_AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_hoyolib_pb_hoyolib_proto_enumTypes[2].Descriptor()
}

func (RegisterRequest_AccountType) Type() protoreflect.EnumType {
	return &file_hoyolib_pb_hoyolib_proto_enumTypes[2]
}

func (x RegisterRequest_AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterRequest_AccountType.Descriptor instead.
func (RegisterRequest_AccountType) EnumDescriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{1, 0}
}

type ResponseHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	UserId  int64  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ResponseHeader) Reset() {
	*x = ResponseHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeader) ProtoMessage() {}

func (x *ResponseHeader) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeader.ProtoReflect.Descriptor instead.
func (*ResponseHeader) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseHeader) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ResponseHeader) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ResponseHeader) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId   string                      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CookieToken string                      `protobuf:"bytes,2,opt,name=cookie_token,json=cookieToken,proto3" json:"cookie_token,omitempty"`
	AccountType RegisterRequest_AccountType `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=hoyolib.RegisterRequest_AccountType" json:"account_type,omitempty"`
	UserId      int64                       `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // send the empty user_id first time to get user_id
	Games       []GameType                  `protobuf:"varint,5,rep,packed,name=games,proto3,enum=hoyolib.GameType" json:"games,omitempty"`
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RegisterRequest) GetCookieToken() string {
	if x != nil {
		return x.CookieToken
	}
	return ""
}

func (x *RegisterRequest) GetAccountType() RegisterRequest_AccountType {
	if x != nil {
		return x.AccountType
	}
	return RegisterRequest_UNKNOWN
}

func (x *RegisterRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterRequest) GetGames() []GameType {
	if x != nil {
		return x.Games
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *ResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type CheckInRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64      `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Games  []GameType `protobuf:"varint,2,rep,packed,name=games,proto3,enum=hoyolib.GameType" json:"games,omitempty"`
}

func (x *CheckInRequest) Reset() {
	*x = CheckInRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInRequest) ProtoMessage() {}

func (x *CheckInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInRequest.ProtoReflect.Descriptor instead.
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{3}
}

func (x *CheckInRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckInRequest) GetGames() []GameType {
	if x != nil {
		return x.Games
	}
	return nil
}

type CheckInResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header             *ResponseHeader                          `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	CheckInInfoCN      map[int32]*CheckInResponse_CheckInStatus `protobuf:"bytes,2,rep,name=CheckInInfoCN,proto3" json:"CheckInInfoCN,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CheckInInfoOversea map[int32]*CheckInResponse_CheckInStatus `protobuf:"bytes,3,rep,name=CheckInInfoOversea,proto3" json:"CheckInInfoOversea,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CheckInResponse) Reset() {
	*x = CheckInResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse) ProtoMessage() {}

func (x *CheckInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse.ProtoReflect.Descriptor instead.
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{4}
}

func (x *CheckInResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *CheckInResponse) GetCheckInInfoCN() map[int32]*CheckInResponse_CheckInStatus {
	if x != nil {
		return x.CheckInInfoCN
	}
	return nil
}

func (x *CheckInResponse) GetCheckInInfoOversea() map[int32]*CheckInResponse_CheckInStatus {
	if x != nil {
		return x.CheckInInfoOversea
	}
	return nil
}

type AccountInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *AccountInfoRequest) Reset() {
	*x = AccountInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoRequest) ProtoMessage() {}

func (x *AccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoRequest.ProtoReflect.Descriptor instead.
func (*AccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{5}
}

func (x *AccountInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type AccountInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *ResponseHeader                  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	AccountInfo *AccountInfoResponse_AccountInfo `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
}

func (x *AccountInfoResponse) Reset() {
	*x = AccountInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoResponse) ProtoMessage() {}

func (x *AccountInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoResponse.ProtoReflect.Descriptor instead.
func (*AccountInfoResponse) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{6}
}

func (x *AccountInfoResponse) GetHeader() *ResponseHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AccountInfoResponse) GetAccountInfo() *AccountInfoResponse_AccountInfo {
	if x != nil {
		return x.AccountInfo
	}
	return nil
}

type CheckInResponse_CheckInStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Msg     string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CheckInResponse_CheckInStatus) Reset() {
	*x = CheckInResponse_CheckInStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckInResponse_CheckInStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckInResponse_CheckInStatus) ProtoMessage() {}

func (x *CheckInResponse_CheckInStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckInResponse_CheckInStatus.ProtoReflect.Descriptor instead.
func (*CheckInResponse_CheckInStatus) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{4, 0}
}

func (x *CheckInResponse_CheckInStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckInResponse_CheckInStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type AccountInfoResponse_AccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameInfos []*AccountInfoResponse_AccountInfo_GameInfo `protobuf:"bytes,1,rep,name=game_infos,json=gameInfos,proto3" json:"game_infos,omitempty"`
	IsSign    bool                                        `protobuf:"varint,2,opt,name=is_sign,json=isSign,proto3" json:"is_sign,omitempty"`
}

func (x *AccountInfoResponse_AccountInfo) Reset() {
	*x = AccountInfoResponse_AccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoResponse_AccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoResponse_AccountInfo) ProtoMessage() {}

func (x *AccountInfoResponse_AccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoResponse_AccountInfo.ProtoReflect.Descriptor instead.
func (*AccountInfoResponse_AccountInfo) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{6, 0}
}

func (x *AccountInfoResponse_AccountInfo) GetGameInfos() []*AccountInfoResponse_AccountInfo_GameInfo {
	if x != nil {
		return x.GameInfos
	}
	return nil
}

func (x *AccountInfoResponse_AccountInfo) GetIsSign() bool {
	if x != nil {
		return x.IsSign
	}
	return false
}

type AccountInfoResponse_AccountInfo_GameInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AccountInfoResponse_AccountInfo_GameInfo) Reset() {
	*x = AccountInfoResponse_AccountInfo_GameInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountInfoResponse_AccountInfo_GameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountInfoResponse_AccountInfo_GameInfo) ProtoMessage() {}

func (x *AccountInfoResponse_AccountInfo_GameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hoyolib_pb_hoyolib_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountInfoResponse_AccountInfo_GameInfo.ProtoReflect.Descriptor instead.
func (*AccountInfoResponse_AccountInfo_GameInfo) Descriptor() ([]byte, []int) {
	return file_hoyolib_pb_hoyolib_proto_rawDescGZIP(), []int{6, 0, 0}
}

var File_hoyolib_pb_hoyolib_proto protoreflect.FileDescriptor

var file_hoyolib_pb_hoyolib_proto_rawDesc = []byte{
	0x0a, 0x18, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x5f, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x79,
	0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x68, 0x6f, 0x79, 0x6f,
	0x6c, 0x69, 0x62, 0x22, 0x57, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8f, 0x02, 0x0a,
	0x0f, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x47, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c,
	0x69, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x2f, 0x0a,
	0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4f, 0x56, 0x45,
	0x52, 0x53, 0x45, 0x41, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x43, 0x4e, 0x10, 0x02, 0x22, 0x43,
	0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x27,
	0x0a, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x05, 0x67, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x8d, 0x04, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x6f,
	0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x0d,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x4e, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x4e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x4e, 0x12,
	0x60, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x76,
	0x65, 0x72, 0x73, 0x65, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x68, 0x6f,
	0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66,
	0x6f, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x12, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65,
	0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x1a, 0x68,
	0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x4e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x6d, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x49, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x4f, 0x76, 0x65, 0x72, 0x73, 0x65, 0x61, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2d, 0x0a, 0x12, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x9a, 0x02, 0x0a, 0x13, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x4b, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x84, 0x01, 0x0a,
	0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x50, 0x0a, 0x0a,
	0x67, 0x61, 0x6d, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x69, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x0a, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x2a, 0x7a, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x15, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x5f, 0x50, 0x41, 0x52, 0x41,
	0x4d, 0x10, 0x90, 0x4e, 0x12, 0x16, 0x0a, 0x11, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x43, 0x52,
	0x45, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x91, 0x4e, 0x12, 0x1c, 0x0a, 0x17,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x52,
	0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x92, 0x4e, 0x12, 0x13, 0x0a, 0x0e, 0x45, 0x52,
	0x52, 0x4f, 0x52, 0x5f, 0x43, 0x48, 0x45, 0x43, 0x4b, 0x5f, 0x49, 0x4e, 0x10, 0x93, 0x4e, 0x2a,
	0x39, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x47, 0x41, 0x4d, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x07, 0x47, 0x65, 0x6e, 0x73, 0x68, 0x69, 0x6e, 0x10, 0xe8, 0x07, 0x12, 0x0d, 0x0a, 0x08, 0x53,
	0x74, 0x61, 0x72, 0x52, 0x61, 0x69, 0x6c, 0x10, 0xe9, 0x07, 0x32, 0xdb, 0x01, 0x0a, 0x07, 0x48,
	0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x12, 0x41, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x12, 0x18, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x68,
	0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x49, 0x6e, 0x12, 0x17, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e,
	0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x2e, 0x68, 0x6f,
	0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c,
	0x69, 0x62, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x68, 0x6f,
	0x79, 0x6f, 0x6c, 0x69, 0x62, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hoyolib_pb_hoyolib_proto_rawDescOnce sync.Once
	file_hoyolib_pb_hoyolib_proto_rawDescData = file_hoyolib_pb_hoyolib_proto_rawDesc
)

func file_hoyolib_pb_hoyolib_proto_rawDescGZIP() []byte {
	file_hoyolib_pb_hoyolib_proto_rawDescOnce.Do(func() {
		file_hoyolib_pb_hoyolib_proto_rawDescData = protoimpl.X.CompressGZIP(file_hoyolib_pb_hoyolib_proto_rawDescData)
	})
	return file_hoyolib_pb_hoyolib_proto_rawDescData
}

var file_hoyolib_pb_hoyolib_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_hoyolib_pb_hoyolib_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_hoyolib_pb_hoyolib_proto_goTypes = []interface{}{
	(ErrorCode)(0),                          // 0: hoyolib.ErrorCode
	(GameType)(0),                           // 1: hoyolib.GameType
	(RegisterRequest_AccountType)(0),        // 2: hoyolib.RegisterRequest.AccountType
	(*ResponseHeader)(nil),                  // 3: hoyolib.ResponseHeader
	(*RegisterRequest)(nil),                 // 4: hoyolib.RegisterRequest
	(*RegisterResponse)(nil),                // 5: hoyolib.RegisterResponse
	(*CheckInRequest)(nil),                  // 6: hoyolib.CheckInRequest
	(*CheckInResponse)(nil),                 // 7: hoyolib.CheckInResponse
	(*AccountInfoRequest)(nil),              // 8: hoyolib.AccountInfoRequest
	(*AccountInfoResponse)(nil),             // 9: hoyolib.AccountInfoResponse
	(*CheckInResponse_CheckInStatus)(nil),   // 10: hoyolib.CheckInResponse.CheckInStatus
	nil,                                     // 11: hoyolib.CheckInResponse.CheckInInfoCNEntry
	nil,                                     // 12: hoyolib.CheckInResponse.CheckInInfoOverseaEntry
	(*AccountInfoResponse_AccountInfo)(nil), // 13: hoyolib.AccountInfoResponse.AccountInfo
	(*AccountInfoResponse_AccountInfo_GameInfo)(nil), // 14: hoyolib.AccountInfoResponse.AccountInfo.GameInfo
}
var file_hoyolib_pb_hoyolib_proto_depIdxs = []int32{
	2,  // 0: hoyolib.RegisterRequest.account_type:type_name -> hoyolib.RegisterRequest.AccountType
	1,  // 1: hoyolib.RegisterRequest.games:type_name -> hoyolib.GameType
	3,  // 2: hoyolib.RegisterResponse.header:type_name -> hoyolib.ResponseHeader
	1,  // 3: hoyolib.CheckInRequest.games:type_name -> hoyolib.GameType
	3,  // 4: hoyolib.CheckInResponse.header:type_name -> hoyolib.ResponseHeader
	11, // 5: hoyolib.CheckInResponse.CheckInInfoCN:type_name -> hoyolib.CheckInResponse.CheckInInfoCNEntry
	12, // 6: hoyolib.CheckInResponse.CheckInInfoOversea:type_name -> hoyolib.CheckInResponse.CheckInInfoOverseaEntry
	3,  // 7: hoyolib.AccountInfoResponse.header:type_name -> hoyolib.ResponseHeader
	13, // 8: hoyolib.AccountInfoResponse.account_info:type_name -> hoyolib.AccountInfoResponse.AccountInfo
	10, // 9: hoyolib.CheckInResponse.CheckInInfoCNEntry.value:type_name -> hoyolib.CheckInResponse.CheckInStatus
	10, // 10: hoyolib.CheckInResponse.CheckInInfoOverseaEntry.value:type_name -> hoyolib.CheckInResponse.CheckInStatus
	14, // 11: hoyolib.AccountInfoResponse.AccountInfo.game_infos:type_name -> hoyolib.AccountInfoResponse.AccountInfo.GameInfo
	4,  // 12: hoyolib.Hoyolib.Register:input_type -> hoyolib.RegisterRequest
	6,  // 13: hoyolib.Hoyolib.CheckIn:input_type -> hoyolib.CheckInRequest
	8,  // 14: hoyolib.Hoyolib.GetAccountInfo:input_type -> hoyolib.AccountInfoRequest
	5,  // 15: hoyolib.Hoyolib.Register:output_type -> hoyolib.RegisterResponse
	7,  // 16: hoyolib.Hoyolib.CheckIn:output_type -> hoyolib.CheckInResponse
	9,  // 17: hoyolib.Hoyolib.GetAccountInfo:output_type -> hoyolib.AccountInfoResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_hoyolib_pb_hoyolib_proto_init() }
func file_hoyolib_pb_hoyolib_proto_init() {
	if File_hoyolib_pb_hoyolib_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hoyolib_pb_hoyolib_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckInResponse_CheckInStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoResponse_AccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hoyolib_pb_hoyolib_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountInfoResponse_AccountInfo_GameInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hoyolib_pb_hoyolib_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hoyolib_pb_hoyolib_proto_goTypes,
		DependencyIndexes: file_hoyolib_pb_hoyolib_proto_depIdxs,
		EnumInfos:         file_hoyolib_pb_hoyolib_proto_enumTypes,
		MessageInfos:      file_hoyolib_pb_hoyolib_proto_msgTypes,
	}.Build()
	File_hoyolib_pb_hoyolib_proto = out.File
	file_hoyolib_pb_hoyolib_proto_rawDesc = nil
	file_hoyolib_pb_hoyolib_proto_goTypes = nil
	file_hoyolib_pb_hoyolib_proto_depIdxs = nil
}
