// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: opwx_pb/opwx.proto

package opwx_pb

import (
	hoyolib_pb "./hoyolib_pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushStatus int32

const (
	PushStatus_OK  PushStatus = 0
	PushStatus_ERR PushStatus = 1
)

// Enum value maps for PushStatus.
var (
	PushStatus_name = map[int32]string{
		0: "OK",
		1: "ERR",
	}
	PushStatus_value = map[string]int32{
		"OK":  0,
		"ERR": 1,
	}
)

func (x PushStatus) Enum() *PushStatus {
	p := new(PushStatus)
	*p = x
	return p
}

func (x PushStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_opwx_pb_opwx_proto_enumTypes[0].Descriptor()
}

func (PushStatus) Type() protoreflect.EnumType {
	return &file_opwx_pb_opwx_proto_enumTypes[0]
}

func (x PushStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushStatus.Descriptor instead.
func (PushStatus) EnumDescriptor() ([]byte, []int) {
	return file_opwx_pb_opwx_proto_rawDescGZIP(), []int{0}
}

type CheckinResults struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*hoyolib_pb.CheckInResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *CheckinResults) Reset() {
	*x = CheckinResults{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opwx_pb_opwx_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckinResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckinResults) ProtoMessage() {}

func (x *CheckinResults) ProtoReflect() protoreflect.Message {
	mi := &file_opwx_pb_opwx_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckinResults.ProtoReflect.Descriptor instead.
func (*CheckinResults) Descriptor() ([]byte, []int) {
	return file_opwx_pb_opwx_proto_rawDescGZIP(), []int{0}
}

func (x *CheckinResults) GetResults() []*hoyolib_pb.CheckInResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type PushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status PushStatus `protobuf:"varint,1,opt,name=status,proto3,enum=opwx.PushStatus" json:"status,omitempty"`
	Msg    string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *PushResponse) Reset() {
	*x = PushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_opwx_pb_opwx_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushResponse) ProtoMessage() {}

func (x *PushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opwx_pb_opwx_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushResponse.ProtoReflect.Descriptor instead.
func (*PushResponse) Descriptor() ([]byte, []int) {
	return file_opwx_pb_opwx_proto_rawDescGZIP(), []int{1}
}

func (x *PushResponse) GetStatus() PushStatus {
	if x != nil {
		return x.Status
	}
	return PushStatus_OK
}

func (x *PushResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_opwx_pb_opwx_proto protoreflect.FileDescriptor

var file_opwx_pb_opwx_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6f, 0x70, 0x77, 0x78, 0x5f, 0x70, 0x62, 0x2f, 0x6f, 0x70, 0x77, 0x78, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6f, 0x70, 0x77, 0x78, 0x1a, 0x18, 0x68, 0x6f, 0x79, 0x6f,
	0x6c, 0x69, 0x62, 0x5f, 0x70, 0x62, 0x2f, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x68, 0x6f, 0x79, 0x6f, 0x6c, 0x69,
	0x62, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x22, 0x4a, 0x0a, 0x0c, 0x50, 0x75,
	0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6f, 0x70, 0x77,
	0x78, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x1d, 0x0a, 0x0a, 0x50, 0x75, 0x73, 0x68, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x45, 0x52, 0x52, 0x10, 0x01, 0x32, 0x48, 0x0a, 0x04, 0x4f, 0x70, 0x77, 0x78, 0x12, 0x40, 0x0a,
	0x12, 0x50, 0x75, 0x73, 0x68, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x12, 0x14, 0x2e, 0x6f, 0x70, 0x77, 0x78, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x12, 0x2e, 0x6f, 0x70, 0x77, 0x78,
	0x2e, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x6f, 0x70, 0x77, 0x78, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_opwx_pb_opwx_proto_rawDescOnce sync.Once
	file_opwx_pb_opwx_proto_rawDescData = file_opwx_pb_opwx_proto_rawDesc
)

func file_opwx_pb_opwx_proto_rawDescGZIP() []byte {
	file_opwx_pb_opwx_proto_rawDescOnce.Do(func() {
		file_opwx_pb_opwx_proto_rawDescData = protoimpl.X.CompressGZIP(file_opwx_pb_opwx_proto_rawDescData)
	})
	return file_opwx_pb_opwx_proto_rawDescData
}

var file_opwx_pb_opwx_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_opwx_pb_opwx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_opwx_pb_opwx_proto_goTypes = []interface{}{
	(PushStatus)(0),                    // 0: opwx.PushStatus
	(*CheckinResults)(nil),             // 1: opwx.CheckinResults
	(*PushResponse)(nil),               // 2: opwx.PushResponse
	(*hoyolib_pb.CheckInResponse)(nil), // 3: hoyolib.CheckInResponse
}
var file_opwx_pb_opwx_proto_depIdxs = []int32{
	3, // 0: opwx.CheckinResults.results:type_name -> hoyolib.CheckInResponse
	0, // 1: opwx.PushResponse.status:type_name -> opwx.PushStatus
	1, // 2: opwx.Opwx.PushCheckinResults:input_type -> opwx.CheckinResults
	2, // 3: opwx.Opwx.PushCheckinResults:output_type -> opwx.PushResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_opwx_pb_opwx_proto_init() }
func file_opwx_pb_opwx_proto_init() {
	if File_opwx_pb_opwx_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_opwx_pb_opwx_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckinResults); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_opwx_pb_opwx_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_opwx_pb_opwx_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opwx_pb_opwx_proto_goTypes,
		DependencyIndexes: file_opwx_pb_opwx_proto_depIdxs,
		EnumInfos:         file_opwx_pb_opwx_proto_enumTypes,
		MessageInfos:      file_opwx_pb_opwx_proto_msgTypes,
	}.Build()
	File_opwx_pb_opwx_proto = out.File
	file_opwx_pb_opwx_proto_rawDesc = nil
	file_opwx_pb_opwx_proto_goTypes = nil
	file_opwx_pb_opwx_proto_depIdxs = nil
}
